
export enum ViewType {
  HOME = 'HOME',
  DICAS = 'DICAS',
  PROFISSIONAIS = 'PROFISSIONAIS',
  APP_EXEMPLO = 'APP_EXEMPLO', // Atua como "Desenvolvimento"
  ESTAGIOS = 'ESTAGIOS',
  SAIBA_MAIS = 'SAIBA_MAIS',
  CONCURSOS = 'CONCURSOS',
  PROJETOS = 'PROJETOS',
  EVENTOS = 'EVENTOS',
  COORDENADOR = 'COORDENADOR',
  EMPREENDEDOR = 'EMPREENDEDOR'
}
