
export enum ViewType {
  HOME = 'HOME',
  DICAS = 'DICAS',
  APP_EXEMPLO = 'APP_EXEMPLO',
  ESTAGIOS = 'ESTAGIOS',
  SAIBA_MAIS = 'SAIBA_MAIS',
  CONCURSOS = 'CONCURSOS',
  PROJETOS = 'PROJETOS',
  COORDENADOR = 'COORDENADOR'
}
